### ISSUE TITLE
nvm path is not in $PATH variabale

### ISSUE THREAD

**Issue by inetufo** [koenpunt/capistrano-nvm#3]
``` rb
  task :start do
    on roles(:app) do
      execute :which, "node"
      execute :echo, "$PATH"
      execute "node --version"
    end
  end
```

``` sh
 INFO [3b311430] Running /usr/bin/env which node on 192.168.1.160
DEBUG [3b311430] Command: ( PATH=/home/deploy/.nvm/v0.10.28/bin:$PATH NODE_VERSI
ON=v0.10.28 /usr/bin/env which node )
DEBUG [3b311430]        /home/deploy/.nvm/v0.10.28/bin/node
 INFO [3b311430] Finished in 0.032 seconds with exit status 0 (successful).
 INFO [41231ec4] Running /usr/bin/env echo $PATH on 192.168.1.160
DEBUG [41231ec4] Command: ( PATH=/home/deploy/.nvm/v0.10.28/bin:$PATH NODE_VERSI
ON=v0.10.28 /usr/bin/env echo $PATH )
DEBUG [41231ec4]        /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:
/bin:/usr/games
 INFO [41231ec4] Finished in 0.056 seconds with exit status 0 (successful).
 INFO [55a9c16b] Running /usr/bin/env node --version on 192.168.1.160
DEBUG [55a9c16b] Command: node --version
DEBUG [55a9c16b]        bash: node: ���������������
cap aborted!
SSHKit::Command::Failed: node --version exit status: 127
node --version stdout: Nothing written
node --version stderr: bash: node: ���������������
D:/Ruby200/lib/ruby/gems/2.0.0/gems/sshkit-1.4.0/lib/sshkit/command.rb:98:in `ex
it_status='
D:/Ruby200/lib/ruby/gems/2.0.0/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:1
42:in `block (4 levels) in _execute'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/channel
.rb:551:in `call'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/channel
.rb:551:in `do_request'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/session
.rb:561:in `channel_request'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/session
.rb:465:in `dispatch_incoming_packets'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/session
.rb:221:in `preprocess'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/session
.rb:205:in `process'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/session
.rb:169:in `block in loop'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/session
.rb:169:in `loop'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/session
.rb:169:in `loop'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/channel
.rb:269:in `wait'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:1
64:in `block (2 levels) in _execute'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/channel
.rb:514:in `call'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/channel
.rb:514:in `do_open_confirmation'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/session
.rb:545:in `channel_open_confirmation'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/session
.rb:465:in `dispatch_incoming_packets'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/session
.rb:221:in `preprocess'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/session
.rb:205:in `process'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/session
.rb:169:in `block in loop'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/session
.rb:169:in `loop'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.0/lib/net/ssh/connection/session
.rb:169:in `loop'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:1
66:in `block in _execute'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:1
23:in `tap'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:1
23:in `_execute'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:6
6:in `execute'
E:/westward-server/game-server/lib/capistrano/tasks/westward.rake:21:in `block (
3 levels) in <top (required)>'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:5
4:in `instance_exec'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:5
4:in `run'
D:/Ruby200/lib/ruby/gems/2.0.0/gems/sshkit-1.4.0/lib/sshkit/runners/parallel.rb:
12:in `block (2 levels) in execute'
Tasks: TOP => deploy:start
```

**Comment by siriniok** [comment]
What to do if I need to run task like this?

execute "cd #{release_path}/frontend && npm install"
